// demo/004. 执行 100 万个任务/react-ts-vite/src/App.tsx
import { useState } from 'react'
import DirectTask from './components/DirectTask'
import SetTimeoutTask from './components/SetTimeoutTask'
import IdleCallbackTask from './components/IdleCallbackTask'
import WorkerTask from './components/WorkerTask'

type Method = 'direct' | 'setTimeout' | 'idleCallback' | 'worker'

const TABS: { key: Method; label: string; desc: string }[] = [
  { key: 'direct', label: '方法一: 直接执行', desc: '同步循环，主线程完全阻塞（对比用）' },
  { key: 'setTimeout', label: '方法二: setTimeout 分片', desc: '分批执行 + setTimeout 让出主线程' },
  { key: 'idleCallback', label: '方法三: requestIdleCallback', desc: '利用浏览器空闲时间执行' },
  { key: 'worker', label: '方法四: Web Worker', desc: '独立线程执行，主线程零阻塞（推荐）' },
]

export default function App() {
  const [method, setMethod] = useState<Method>('worker')

  const current = TABS.find((t) => t.key === method)!

  return (
    <div style={{ fontFamily: 'sans-serif', padding: '24px', maxWidth: '800px', margin: '0 auto' }}>
      <h2>React + TS + Vite - 执行 100 万个任务</h2>
      <p style={{ color: '#888', fontSize: '14px', marginBottom: '20px' }}>
        演示在浏览器中执行 100 万个计算任务时，不同方案对页面流畅度的影响。
      </p>

      {/* 方法切换 Tab */}
      <div style={{ display: 'flex', gap: '8px', marginBottom: '16px', flexWrap: 'wrap' }}>
        {TABS.map((tab) => (
          <button
            key={tab.key}
            onClick={() => setMethod(tab.key)}
            style={{
              padding: '8px 16px',
              background: method === tab.key ? '#1677ff' : '#fff',
              color: method === tab.key ? '#fff' : '#333',
              border: '1px solid #ddd',
              borderRadius: '4px',
              cursor: 'pointer',
              fontSize: '14px',
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* 当前方法说明 */}
      <div
        style={{
          marginBottom: '20px',
          padding: '10px 16px',
          background: '#f5f5f5',
          borderRadius: '6px',
          color: '#666',
          fontSize: '14px',
        }}
      >
        {current.desc}
      </div>

      {/* 任务执行区域 */}
      <div
        style={{
          padding: '20px',
          border: '1px solid #e8e8e8',
          borderRadius: '8px',
          background: '#fff',
        }}
      >
        {method === 'direct' && <DirectTask />}
        {method === 'setTimeout' && <SetTimeoutTask />}
        {method === 'idleCallback' && <IdleCallbackTask />}
        {method === 'worker' && <WorkerTask />}
      </div>
    </div>
  )
}

// demo/001. 超大树形结构数据/vue2/src/App.vue
<template>
  <div style="font-family: sans-serif; padding: 24px; max-width: 900px; margin: 0 auto">
    <h2>Vue2 - 超大树形数据处理</h2>

    <!-- 数据生成控制面板 -->
    <div style="padding: 16px; background: #f5f5f5; border-radius: 8px; margin-bottom: 16px">
      <h3 style="margin-top: 0">模拟后端一次性返回的超大树形数据</h3>
      <div style="display: flex; gap: 24px; align-items: center; flex-wrap: wrap">
        <label>
          树深度:
          <input
            v-model.number="depth"
            type="number"
            min="1"
            max="8"
            style="width: 60px; margin-left: 8px"
          />
        </label>
        <label>
          每层子节点数:
          <input
            v-model.number="breadth"
            type="number"
            min="1"
            max="20"
            style="width: 60px; margin-left: 8px"
          />
        </label>
        <button
          :style="{
            padding: '6px 16px',
            background: '#4caf50',
            color: '#fff',
            border: 'none',
            borderRadius: '4px',
            cursor: 'pointer',
          }"
          @click="handleGenerate"
        >
          {{ loading ? '生成中...' : '生成数据' }}
        </button>
        <span v-if="data.length > 0" style="color: #e65100">
          总节点数: <strong>{{ totalNodes }}</strong>
        </span>
      </div>
      <p style="color: #999; font-size: 13px; margin-bottom: 0">
        提示: 深度5×广度8 ≈ 37448 节点 | 深度5×广度10 ≈ 111110 节点
      </p>
    </div>

    <!-- 方法切换 Tab -->
    <div style="display: flex; gap: 8px; margin-bottom: 16px">
      <button
        v-for="tab in tabs"
        :key="tab.key"
        :style="{
          padding: '8px 16px',
          background: method === tab.key ? '#1976d2' : '#fff',
          color: method === tab.key ? '#fff' : '#333',
          border: '1px solid #ddd',
          borderRadius: '4px',
          cursor: 'pointer',
        }"
        @click="method = tab.key"
      >
        {{ tab.label }}
      </button>
    </div>

    <!-- 当前方法说明 -->
    <div style="margin-bottom: 16px; color: #666; font-size: 14px">
      {{ currentDesc }}
    </div>

    <!-- 树渲染区域 -->
    <normal-tree v-if="data.length > 0 && method === 'normal'" :data="data" />
    <virtual-tree
      v-else-if="data.length > 0 && method === 'virtual'"
      :data="data"
      :default-expand-depth="0"
    />
    <time-slice-tree
      v-else-if="data.length > 0 && method === 'timeSlice'"
      :data="data"
      :default-expand-depth="0"
    />
    <div
      v-else
      :style="{
        height: '500px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        border: '2px dashed #ddd',
        borderRadius: '4px',
        color: '#999',
      }"
    >
      请先生成数据
    </div>
  </div>
</template>

<script>
import { generateBigTree, countNodes } from './utils/treeData'
import NormalTree from './components/NormalTree.vue'
import VirtualTree from './components/VirtualTree.vue'
import TimeSliceTree from './components/TimeSliceTree.vue'

export default {
  name: 'App',
  components: { NormalTree, VirtualTree, TimeSliceTree },
  data() {
    return {
      depth: 5,
      breadth: 8,
      data: [],
      method: 'virtual',
      loading: false,
      tabs: [
        { key: 'normal', label: '方法一: 直接渲染', desc: '递归全量渲染，性能最差（对比用）' },
        { key: 'virtual', label: '方法二: 虚拟列表', desc: '只渲染可视区域，DOM 数恒定（推荐）' },
        { key: 'timeSlice', label: '方法三: 时间分片', desc: '分批渲染节点，避免主线程长时间阻塞' },
      ],
    }
  },
  computed: {
    totalNodes() {
      return countNodes(this.data)
    },
    currentDesc() {
      const tab = this.tabs.find((t) => t.key === this.method)
      return tab ? tab.desc : ''
    },
  },
  methods: {
    handleGenerate() {
      this.loading = true
      // 用 setTimeout 让 UI 先更新 loading 态
      setTimeout(() => {
        this.data = generateBigTree(this.depth, this.breadth)
        this.loading = false
      }, 50)
    },
  },
}
</script>
