// demo/002. 一次性渲染 10 万条数据/vue2/src/components/TimeSliceList.vue
<template>
  <div>
    <div class="status" style="margin-bottom: 8px">
      已渲染 {{ renderedCount.toLocaleString() }} / {{ data.length.toLocaleString() }} 条
      <span v-if="isRendering"> · 渲染中...</span>
    </div>
    <div class="list-container">
      <div v-for="item in visibleData" :key="item.id" class="list-item">
        <span class="idx">#{{ item.id + 1 }}</span>
        <span class="content"> {{ item.name }} - 值: {{ item.value }} - {{ item.desc }} </span>
      </div>
      <div v-if="isRendering" class="loading">加载更多数据...</div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'TimeSliceList',
  props: {
    data: {
      type: Array,
      default: () => [],
    },
    batchSize: {
      type: Number,
      default: 200,
    },
  },
  data() {
    return {
      renderedCount: 0,
      isRendering: false,
      rafId: null,
    }
  },
  computed: {
    visibleData() {
      return this.data.slice(0, this.renderedCount)
    },
  },
  watch: {
    data: {
      handler() {
        this.startRender()
      },
      immediate: true,
    },
  },
  beforeDestroy() {
    this.cancelRaf()
  },
  methods: {
    startRender() {
      this.cancelRaf()
      this.renderedCount = 0
      this.isRendering = true
      this.renderBatch()
    },
    renderBatch() {
      this.renderedCount = Math.min(this.renderedCount + this.batchSize, this.data.length)
      if (this.renderedCount >= this.data.length) {
        this.isRendering = false
        return
      }
      // 让出主线程，下一帧继续渲染下一批
      this.rafId = requestAnimationFrame(this.renderBatch)
    },
    cancelRaf() {
      if (this.rafId !== null) {
        cancelAnimationFrame(this.rafId)
        this.rafId = null
      }
    },
  },
}
</script>

// demo/002. 一次性渲染 10 万条数据/react-ts-vite/src/components/TimeSliceList.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { ListItem } from '../utils/data'

interface Props {
  data: ListItem[]
  batchSize?: number
}

/**
 * 方法三：时间分片（Time Slicing）
 * 核心原理：
 * 1. 不一次性渲染全部 10 万条，而是分批（每批 batchSize 条）追加
 * 2. 每渲染完一批，用 requestAnimationFrame 让出主线程，浏览器有机会响应交互、绘制
 * 3. 重复上述过程直到所有数据渲染完毕
 *
 * 优点：实现简单，不需要计算可视区域；用户能逐步看到内容，不会长时间白屏卡死。
 * 缺点：最终 DOM 数量仍等于数据总量，10 万条 DOM 会占用较多内存，滚动可能不够流畅。
 * 适合中等数据量（几千到一两万），大数据量推荐虚拟列表。
 */
export default function TimeSliceList({ data, batchSize = 200 }: Props) {
  const [renderedCount, setRenderedCount] = useState(0)
  const [isRendering, setIsRendering] = useState(false)
  const rafRef = useRef<number | null>(null)

  const startRender = useCallback(() => {
    // 重置
    setRenderedCount(0)
    setIsRendering(true)
  }, [])

  useEffect(() => {
    if (!isRendering) return

    const renderBatch = () => {
      setRenderedCount((prev) => {
        const next = prev + batchSize
        if (next >= data.length) {
          setIsRendering(false)
          return data.length
        }
        // 让出主线程，下一帧继续渲染下一批
        rafRef.current = requestAnimationFrame(renderBatch)
        return next
      })
    }

    rafRef.current = requestAnimationFrame(renderBatch)

    return () => {
      if (rafRef.current !== null) {
        cancelAnimationFrame(rafRef.current)
      }
    }
  }, [isRendering, data.length, batchSize])

  // 数据变化时自动开始
  useEffect(() => {
    startRender()
  }, [data, startRender])

  const visibleData = data.slice(0, renderedCount)

  return (
    <div>
      <div className="status" style={{ marginBottom: 8 }}>
        已渲染 {renderedCount.toLocaleString()} / {data.length.toLocaleString()} 条
        {isRendering && ' · 渲染中...'}
      </div>
      <div className="list-container">
        {visibleData.map((item) => (
          <div className="list-item" key={item.id}>
            <span className="idx">#{item.id + 1}</span>
            <span className="content">
              {item.name} - 值: {item.value} - {item.desc}
            </span>
          </div>
        ))}
        {isRendering && <div className="loading">加载更多数据...</div>}
      </div>
    </div>
  )
}
